---
kind: pipline
name: mx-auth

platform:
  os: linux
  arch: amd64

steps:

  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dmattox10/mx-auth
      auto_tag: true
      auto_tag_suffix: linux-amd64

# steps:
# - name: build
#   image: docker:latest
#   volumes: 
#     - name: docker_sock
#       path: /var/run/docker.sock
#   environment:
#     REGISTRY_USER:
#       from_secret: REGISTRY_USER
#     REGISTRY_PASS:
#       from_secret: REGISTRY_PASS
#   commands:
#     - docker build --no-cache -t docker.danielmattox.com/mx-auth:latest . -f Dockerfile
# - name: publish
#   image: docker.danielmattox.com/mx-auth:latest